#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
sudo apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 21874-web-01 3.238.201.99:80 check\n\tserver 21874-web-02 3.235.77.73:80 check" >> /etc/haproxy/haproxy.cfg
echo -e ENABLED = 1 >> /etc/default/hyproxy
sudo service haproxy restart

